## pushstate redirect 
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/*.css"
  [headers.values]
    cache-control = '''
    max-age=604800,
    public'''

[[headers]]
  for = "/*.js"
  [headers.values]
    cache-control = '''
    max-age=604800,
    public'''